---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-example
  namespace: secrets
spec:
  selector:
    app: vault-agent-example
  type: NodePort
  ports:
  - port: 80
    targetPort: 80 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-example
  namespace: secrets
  labels: 
    app: vault-agent-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent-example
  template:
    metadata:
      annotations:
      labels:
        app: vault-agent-example
    spec:
      serviceAccountName: vault-auth
      containers:
      - image: nginx
        name: nginx-container
        ports:
        - containerPort: 80
      
